# Defina o nome da pipeline
name: pipeline devops2
# Defina a trigger. Qual evento vai ser disparado pra começar o workflow
# Declarando o push:
on:
  push:
    branches: ["main"] #delcare todas que precisar
  workflow_dispatch: #permite que execute manualmente.
# Declare os jobs.
jobs:
  worflow-devops2:
    name: "Workflow Devops2"
    runs-on: ubuntu-latest #declarando runner
# Declare os passos da execuçao, os steps
    steps: #onde entram as actions
      - name: "Primeira açao"
        run: echo "Hello Devops2"
      - name: "Segunda açao"
        run: |
          echo "Workflow 1"
          echo "Parabéns"
#Declarando e executando o script
      - name: "Script Python"
        run: |
          variavel = "Hello devops2"
          print(variavel)
        shell: python
        
  worflow-nodejs:
    name: "Instalando ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificando versao do Node JS atual"
        run: node --version
# https://github.com/marketplace/actions/setup-node-js-environment      
      - name: "Definição da versao 20.16.0 do Node JS"
      - uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'
      - name: "Verificando versao do Node JS depois de instalado"
        run: node --version
          
  
  
